version: "3.3"
services:
  postgres:
    container_name: postgress
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres