spring:
  datasource:
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    maximumPoolSize: 2
    minimumIdle: 1
    hikari:
      connectionTimeout: 2000
      maximum-pool-size: 100
      maximumPoolSize: 5
      minimumIdle: 1
  flyway:
    user: postgres
    password: mysecretpassword
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/postgres
    locations: classpath:db/migration
    schema: url
    baselineOnMigrate: true
    enabled: true
    schemas: url
    check-location: true